// Generated by CoffeeScript 1.8.0
(function() {
  var colorScale, commaFormat, h, pack, radScale, svg, tooltip, w;

  w = 600;

  h = 600;

  commaFormat = d3.format("0,000");

  tooltip = d3.select("body").append("div").attr("class", "map-tooltip").style("position", "absolute");

  colorScale = d3.scale.ordinal().domain(['Incorporated company', 'Partnership', 'Informal', 'Non-profit', 'Franchisee', 'Not reported', 'Sole proprietorship']).range(['steelblue', 'cornflowerblue', 'red', 'orange', 'limegreen', 'lightgray', 'green']);

  radScale = d3.scale.sqrt().domain([0, 12000]).range([0, 30]);

  pack = d3.layout.pack().sort(function(a, b) {
    return b.value - a.value;
  }).size([w, h]).value(function(d) {
    return d.value;
  }).padding(2).radius(function(d) {
    return radScale(d);
  });

  svg = d3.select("#emp").append("svg").attr("width", w).attr("height", h);

  d3.csv('data/all_vent_contrib.csv', (function(d) {
    return {
      "value": d.employment,
      "name": d.typorg
    };
  }), function(dataCsv) {
    var dataJson, nodes;
    dataJson = d3.nest().key(function(d) {
      return d.name;
    }).entries(dataCsv);
    dataJson.forEach(function(d) {
      return d.children = d.values;
    });
    nodes = pack.nodes({
      children: dataJson
    });
    svg.selectAll("circle").data(nodes).enter().append("circle").attr("r", function(d) {
      return d.r;
    }).attr("cx", function(d) {
      return d.x;
    }).attr("cy", function(d) {
      return d.y;
    }).style("fill", function(d) {
      if (d.children) {
        return "white";
      } else {
        return colorScale(d.parent.key);
      }
    }).on("mouseover", function(d) {
      if (!d.children) {
        return tooltip.html(d.name + " <b>" + commaFormat(d.value) + "</b>").style("left", (d3.event.pageX - 15) + "px").style("top", (d3.event.pageY + 50) + "px").style("opacity", 1);
      }
    }).on("mouseleave", function(d) {
      return tooltip.style("opacity", 0);
    });
  });

}).call(this);
